version: '3.9'

services:
  postgres:
    image: postgres
    env_file:
      - .env/.dev.database.env
    volumes:
      - postgres_dev_data:/var/lib/posgresql/data
    ports:
      - 5432:5432
  api:
    depends_on:
      - postgres
    env_file:
      - .env/.dev.env
    build:
      dockerfile: docker/Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
  client:
    build:
      dockerfile: docker/Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
  nginx:
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

volumes:
  postgres_dev_data:
