version: '3.9'

services:
  api:
    env_file:
      - api/env/.env.dev
    build:
      dockerfile: docker/Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
  client:
    build:
      dockerfile: docker/Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
  nginx:
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
