FROM python:3.11-alpine

ARG ENVIRONMENT

ENV DJANGO_ENV=${ENVIRONMENT} \
  # python:
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  # pip:
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # poetry:
  POETRY_VERSION=1.5.1 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry'

# System deps:
RUN pip install "poetry==$POETRY_VERSION"

# set work directory
WORKDIR /app
COPY pyproject.toml poetry.lock /app/

# Install dependencies:
RUN poetry install --without=dev
# copy project
COPY . .

CMD ["python",  "manage.py",  "runserver", "0.0.0.0:8000"]
